### ISSUE TITLE
Build with CMake

### ISSUE THREAD

**Issue by rouson** [radiasoft/zgoubi#1]
Enable automatic test execution via CTest for (existing) integration tests and (eventual) unit tests.

Tested code is trusted code and that is especially true when applied to refactoring code at the hands of non-experts in the application domain.

**Comment by rouson** [comment]
The deliverable associated with this issue is now ready for review on the [develop] branch.  To test using CMake directly, issue commands like the following:
```bash
git clone -b develop https://github.com/sourceryinstitute/zgoubi
mkdir -p zgoubi/build
cd zgoubi/build
FC=gfortran CC=gcc cmake .. -DCMAKE_INSTALL_PREFIX=/opt/zgoubi
make -j
ctest
make install
```
or use the bash installation script to invoke `cmake`, replacing everything after the first line above with the following:
```
cd zgoubi
./install.sh --with-fortran gfortran --with-c gcc --install-prefix /opt/zgoubi
cd build
ctest
```
Issue the command `./install.sh --help` to see all possible installer arguments, examples of their use, and their default values.  The above has been tested successfully macOS 10.13 High Sierra and Lubuntu Linux 18.04.  It is also likely to work on the Windows Subsystem for Linux ([WSL]) that ships with Windows 10.

[develop]: https://github.com/radiasoft/zgoubi/tree/develop
[WSL]: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by zbeekman** [comment]
@rouson: Should the git clone command be the SI fork? Or has this been pushed back upstream?
