### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by rouson** [radiasoft/zgoubi#10]
[Travis-CI] offers free cycles up to one hour per batch for testing that supports continuous integration (CI) on open-source projects on GitHub.  Sourcery staff and contractors have expertise in setting up Travis-CI for open-source projects and will do so for the open-source, GitHub-hosted [radiasoft/zgoubi] repository, given available tests that fit within the time limit imposed by Travis-CI.

[Travis-CI]: https://www.travis-ci.org
[radiasoft/zgoubi]: https://github.com/radiasoft/zgoubi/

**Comment by zbeekman** [comment]
Continuous integration has been setup and enabled on the [Sourcery Institute fork](https://github.com/sourceryinstitute/zgoubi). The build status can be embedded in a  markdown based README file (.i.e., `README.md` which will be richly displayed on github) and/or in the developer documentation and any other website. Click the build badge below to see the build status on the SI fork's develop branch:

[![Build Status](https://travis-ci.com/sourceryinstitute/zgoubi.svg?branch=develop)](https://travis-ci.com/sourceryinstitute/zgoubi)

The associated continuous integration tests will be posted at https://travis-ci.com/radiasoft/zgoubi once Travis-CI.com is enabled for the organization and zgoubi repository. (Someone with administrative rights to the radiasoft org and zgoubi repo will need to head over to Travis-CI.com to enable this)

The current build matrix tests two environments:

1. macOS with the latest stable version of GCC and GFortran installed through the [Homebrew package manager](https://brew.sh) (currently 8.1)
2. Ubuntu 14.04 with the latest stable release off the 7.x branch of GCC/GFortran, currently 7.3.

Any branch containing the [.travis.yml](https://github.com/sourceryinstitute/zgoubi/blob/develop/.travis.yml) file will get tested if travis-ci.com is enabled for the repository. The test includes:

- Setting up compilation with GCC, GFortran and CMake
- Configuring the project with CMake (#1)
- Compiling the project with Makefiles generated by CMake
- Running all tests defined by CTest (#2)

**Comment by rouson** [comment]
@zbeekman Thanks for the great work!  The deliverable for this issue is ready for review.

**Comment by robnagler** [comment]
Please implement in our environment and remove the Darwin and Ubuntu environments from the travis file. You could do something like this (untested):

```yaml
sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
script:
  - bash travis.sh
```

The travis.sh file might look like (untested):

```sh
set -euo pipefail
docker run -i --rm -u vagrant -v $PWD:/home/vagrant/src/radiasoft/zgoubi radiasoft/beamsim-part1 bash  <<'EOF'
#!/bin/bash
~/.bashrc
set -euo pipefail
cd ~/src/radiasoft/zgoubi
mkdir build
cd build
cmake ..
make test
EOF
```

**Comment by zbeekman** [comment]
@robnagler My instinct would be to add this in addition to the existing test matrix, until we encounter an issue with one of the other builds that's non-trivial, but I happily defer to Radiasoft's preferences.

**Comment by robnagler** [comment]
Let's keep it simple as in https://github.com/radiasoft/zgoubi/issues/10#issuecomment-406699339

**Comment by zbeekman** [comment]
@robnagler 

It took quite a bit of fiddling to determine why testing in the docker image was working on my local machine (macOS) and not on Travis-CI but I now have the CI tests running in the docker image. The issue was that before docker is started the directory being mounted in the docker image needs to be `chown`ed recursively to match the `$UID` of the docker user (`vagrant`, UID=1000). Click the build badge to view the working build on Travis-CI.

[![Build Status](https://travis-ci.org/radiasoft/zgoubi.svg?branch=fix-issue-%2328-fedora-27-build)](https://travis-ci.org/radiasoft/zgoubi/builds/407789840)

Also, I think this resolves #27 but I'll head over that way and re-read the comments so I don't miss anything.

EDIT: And resolves #28

**Comment by robnagler** [comment]
@zbeekman Great work, thanks. Sorry it was so much trouble.

**Comment by zbeekman** [comment]
No worries, I’m glad we can help provide a CI test case that will be
helpful to you.
