### ISSUE TITLE
Test with CTest

### ISSUE THREAD

**Issue by rouson** [radiasoft/zgoubi#2]
To automate the execution of any pre-existing tests, which most likely take the form of integration tests involving complete solutions for known physics requiring multiple compilation units, e.g. multiple subroutines and files.

**Comment by rouson** [comment]
The deliverable associated with this issue is now ready for review on the [develop] branch.  The passing `zgoubi` integration test can be executed using the steps outlined in the comment I just posted on issue #1.  As noted, the test passes on macOS 10.13 High Sierra and Lubuntu Linux 18.04 and would likely pass on the Windows Subsystem for Linux that ships with Windows 10.

**Comment by robnagler** [comment]
Please see https://github.com/radiasoft/zgoubi/issues/32#issue-342776407 for a requested fix to the test.

Once the test is fixed, I'll nuke the repo again. It's important that we avoid adding large files to the repo (#32).
