### ISSUE TITLE
Trim zgoubi repo

### ISSUE THREAD

**Issue by robnagler** [radiasoft/zgoubi#20]
The repo is too large and contains several large files:

```text
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File exemples/RHIC/3DSnakes/fieldMaps/model3a2a-x-4_4_y-4_4_z-180_180-integral.table.gz is 66.67 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File exemples/RHIC/3DSnakes/fieldMaps/model3a2a322a-x-4_4_y-4_4_z-180_180-integral.table.gz is 66.48 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File toolbox/tunesFromFai/tunesFromFai is 68.79 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File toolbox/lipsFitFromFai/lipsFitFromFai is 68.77 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File toolbox/lipsFitFromFai/lipsFitFromFai is 68.78 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

We need to purge these large files from the history. They can stay on SourceForge.

An alternative is to create a new repo of only the source without the the history, which will remain on SourceForge.

**Comment by robnagler** [comment]
@dtabell It would be good to get your opinion on this. Thanks

**Comment by robnagler** [comment]
@dtabell per our discussion, I think it's in your court to decide on how to migrate the repo. 

@rouson you should just proceed with the repo as is. It's been updated with the latest from SourceForge.

**Comment by robnagler** [comment]
@rouson @dtabell I think we should flush the history, compress some of the data files, and remove binaries (PDFs, etc.). This will mean we should apply your (@rouson) pull request commits to the new repo (which I have yet to review).

I'll focus on this today

**Comment by robnagler** [comment]
@rouson I'm about to update zgoubi with a hard reset. This will eliminate debugging, exemples, publications, and toolbox.

**Comment by dtabell** [comment]
Hi Rob,

exemples contains material for testing zgoubi
I think the same is true of toolbox

Dan

**Comment by robnagler** [comment]
Yes, I know. We will add in the parts of exemples and toolbox as they are needed and integrating int CTest.

**Comment by robnagler** [comment]
The hard reset only reset the master, which didn't do what we want. The problem is the branches are in this repo so we need to reset those. I don't want to do that because they contain @rouson's work, which we'll need to replay. Perhaps a call is in order with @rouson. I'm busy right now but could be available later today

**Comment by rouson** [comment]
@robnagler I'm on a call with @dtabell through 4 PM PT.  Feel free to join us if you free up before then.  Tomorrow is pretty flexible for me after 10 AM PT.  

In case it's helpful, binary available/unavaible information is always available for me at https://bit.ly/rouson-calendar and I _think_ I have my calendar set up to automatically accept invitations for times that are open, but I'm not sure that latter feature is working right now.

**Comment by robnagler** [comment]
The git repos is now 1.4M.

@rouson please apply your updates to the master or a pull request if you prefer.

**Comment by robnagler** [comment]
FTR, we have a full backup of the repo before the hard reset. We backup the repo, issues, comments, wiki, etc. every night.

**Comment by robnagler** [comment]
It looks like the ctest and develop branches were not a clean commit, but applied the entire history as well including exemples, publications, etc. so we are back to a 1.5GB checkout.

I'm going to flush the history on all the branches. We'll lose the pull requests again, sorry.

**Comment by robnagler** [comment]
develop and ctest have been trimmed. Back to 12M checkout.
