### ISSUE TITLE
create token for zgoubi.github.io

### ISSUE THREAD

**Issue by robnagler** [radiasoft/zgoubi#26]
give to @rouson

**Comment by zbeekman** [comment]
@robnagler Is this to push up the FORD API documentation? Might be better to give to me, or you could just create an encrypted variable either through [the Travis-CI.org web UI](https://travis-ci.org/radiasoft/zgoubi/settings) or [using the `travis` ruby gem](https://docs.travis-ci.com/user/encryption-keys/#usage) to add it to `.travis.yml`.

In the past, I have always found it was easier to prevent GH authentication from leaking by using an encrypted SSH keypair made specifically for this purpose, possibly from a phony/bot account on GH. Sometimes when git runs into issues with commands that manipulate the remote, the GH token can get printed to the screen. Using public/private SSH key authentication makes it less likely that a secret will end up in a publicly viewable log.

However, using a token is easier to setup, so I'm happy with whatever your preference is.

**Comment by robnagler** [comment]
Yes, this is to push the doc builds. I don't think it is so important yet so no point in doing anything. We need a home page for zgoubi.com so let's just wait.
