### ISSUE TITLE
Replace legacy features

### ISSUE THREAD

**Issue by rouson** [radiasoft/zgoubi#3]
Prerequisite
------------
Because this item requires changing the code, item 1 of issue #2 must be completed first to give us some confidence that our changes are not breaking anything.  We should automate processes wherever possible using refactoring tools and we should focus first on parts of the software that are covered by the tests.

Tasks
------
The following were discussed in the initial teleconferences.

   - [ ] Convert from fixed-source form to free-source form.  
   - [ ] Convert/wrap`common` blocks to/in `module`s.
   - [ ] Replace `include` with `use`.

For additional suggestions, see [Rouson et al. (2015)] and [Norton and Decyk (2000)].  

[Rouson et al. (2015)]: https://dl.acm.org/citation.cfm?id=2814699
[Norton and Decyk (2000)]: https://trs.jpl.nasa.gov/bitstream/handle/2014/16478/00-2536.pdf?sequence=1

**Comment by robnagler** [comment]
Replaced with #16 and #17.
