### ISSUE TITLE
Certain input files can generate massive amounts of unprintable output data

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/zgoubi#48]
As noticed by @moellep.  See the attached file [zgoubi_disk_fill.dat.gz](https://github.com/radiasoft/zgoubi/files/2586314/zgoubi_disk_fill.dat.gz) which spews gigabytes of garbage (in this case it looks like 4MB of 0s per particle, as revealed in a hex editor).  **Note that code built from the master branch at sourceforge handles the file properly**.  The two forks are quite different at this point - perhaps this was already addressed?  Anyway here's an issue for it.

**Comment by bnash** [comment]
When I run this input file with zgoubi built on my mac, for the most recent github version, I get the output:

Title :                                                                                 

    1/   16 OPTIONS   /                    /                                    
+
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x127816f3c
#1  0x1278162e3
#2  0x7fffbea40b39
Segmentation fault: 11
