### ISSUE TITLE
Set up the required particle data distribution across images

### ISSUE THREAD

**Issue by rouson** [radiasoft/zgoubi#70]
**Prerequisite:** input files (example: `*.dat` file corresponding to a `*.res` file with `OBJET=3`)

### Budget and Timeline Risk Factors ###

It is difficult to estimate the amount of work involved in completing the items designated in **bold** font below. Depending on the complexity of what we discover in the course of this SOW, completing the **bold** items might require either 
1. Offloading much of the supporting work to RadiaSoft or
2. A separate SOW to be billed on an hourly basis. 

### Steps ###

- [x] Identify arrays that hold particle state vectors with one dimension corresponding to a unique particle identification (ID) number. 
  -  _Example_: arrays `LET`, `IEX`, `FO`, and `SI` at [`obj3.f` line 448].
- [x] Partition particle ID ownership evenly across images.
- [x] **Identify `DO` loops over particle ID in the code blocks exercised by the chosen test.**
  - _Example_: `DO IT = 1,IMAX` at `transf.f` line [110].
- [x] Not needed: **Identify _implicit_ loops over particle ID in the code blocks exercised by the chosen test.**
  - _Example_: the implicit loop that starts at [`222 CONTINUE`] in `obj3.f`, terminates at one of the jumps to statement labels [95] or [97], and sets `IED`, which potentially plays a role in terminating another implicit loop starting at [`221 CONTINUE`]
- [ ] **Optional:** convert `GOTO`/`CONTINUE` loops to `DO`/`END DO` to clarify the  program control flow.
- [x] **Restrict computation on each image to the particles owned by the given image** 
   - _Example_: change the above `DO` loop to `DO IT = my_first, my_last` or `DO CONCURRENT...`.

[`222 CONTINUE`]: https://github.com/radiasoft/zgoubi/blob/parallel-particle/zgoubi/obj3.f#L191
[`221 CONTINUE`]: https://github.com/radiasoft/zgoubi/blob/parallel-particle/zgoubi/obj3.f#L230

[ 110]: https://github.com/radiasoft/zgoubi/blob/fix-common-blocks/zgoubi/transf.f#L110
[95]: https://github.com/radiasoft/zgoubi/blob/fix-common-blocks/zgoubi/obj3.f#L524
[97]: https://github.com/radiasoft/zgoubi/blob/fix-common-blocks/zgoubi/obj3.f#L520
[`obj3.f` line 448]: https://github.com/radiasoft/zgoubi/blob/fix-common-blocks/zgoubi/obj3.f#L448

**Comment by dtabell** [comment]
All necessary parts completed.
