### ISSUE TITLE
Implement inter-image communication

### ISSUE THREAD

**Issue by rouson** [radiasoft/zgoubi#71]
### Budget and Timeline Risk Factors ###
It is difficult to estimate the amount of work involved in completing the item designated in **bold** font below.  Depending on the complexity of what we discover in the course of this SOW, completing the **bold** items might require either
1. Offloading much of the supporting work to RadiaSoft or
2. A separate SOW to be billed on an hourly basis.

### Steps ###

- [x] Set up image 1 to handle all file input/output.
- [x] Distribute or gather data between image 1 and other images as necessary.

**Comment by dtabell** [comment]
Image 1 correctly `gather`s data from the other images, but restricting file output to image 1 causes a crash. This has been reported as a bug. See issue #80.
