### ISSUE TITLE
Create test for electric field tracking

### ISSUE THREAD

**Issue by bnash** [radiasoft/zgoubi#83]
We need a test to make sure we cover tracking through electric fields.
I added the following test in the `add-zgoubi-tests` branch using `elmult` electric multipole elements.
https://github.com/radiasoft/zgoubi/tree/add-zgoubi-tests/tests/elmult

We should make sure this test is adequate for the purpose.

**Comment by dtabell** [comment]
This is a prerequisite for #81

**Comment by bnash** [comment]
Wien filter test has been implemented. 3e2972ee0383109cf67cea8a46956771ea297927
This element contains both electric and magnetic fields.
